export const AppIcons = {
  wallet: "account-balance-wallet",
  home: "home",
  profile: "person",
  lastName: "badge",
  phone: "phone",
  settings: "settings",
  privacy: "privacy-tip",
  backArrow: "arrow-back",
  forwardArrow: "arrow-forward",
  add: "add",
  edit: "edit",
  delete: "delete",
  search: "search",
  filter: "filter-list",
  calendar: "calendar-today",
  category: "category",
  budget: "account-balance",
  analytics: "bar-chart",
  income: "trending-up",
  expense: "trending-down",
  notification: "notifications",
  eyeOpen: "visibility",
  eyeClosed: "visibility-off",
  logout: "logout",
  close: "close",
  check: "check-circle",
  error: "error",
  camera: "photo-camera",
  gallery: "image",
  menu:"menu",
  amount: "attach-money",
  note: "notes",
  receipt: "receipt-long",
  expenseTitle: "short-text",
  darkMode: "dark-mode",
  lightMode: "light-mode",
  language: "translate",
  info: "info-outline",
  chevronRight: "chevron-right",
} as const;

export type AppIconName = (typeof AppIcons)[keyof typeof AppIcons];